version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - .database:/var/lib/postgresql/data
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8082:8080
#  axon-server:
#    image: "axoniq/axonserver"
#    hostname: axon-server
#    environment:
#      - AXONSERVER_EVENTSTORE=/eventstore
#      - AXONSERVER_CONTROLDB=/controldb
#    volumes:
#      - .axonserver-eventstore:/eventstore
#      - .axonserver-controldb:/controldb
#    ports:
#      - '8024:8024'
#      - '8124:8124'

volumes:
  .database:
#  .axonserver-eventstore:
#  .axonserver-controldb: